const therapistsData = [
    {
      id: "1",
      name: "Dr. Ketan Parmar",
      specialization: "Psychologist",
      experience: "37 years experience overall",
      location: "Borivali East, Mumbai",
      rating: 74,
      reviews: 31,
      available: "Available Tomorrow",
      image: require("../assets/images/dr-ketan.jpg"),
    },
    {
      id: "2",
      name: "Dr. Naazneen Ladak",
      specialization: "Psychologist",
      experience: "21 years experience overall",
      location: "Andheri West, Mumbai  BHN Elder Care + 2 more",
      rating: 98,
      reviews: 82,
      available: "Available Today",
      image: require("../assets/images/dr-naazneen-ladak.jpg"),
    },
    {
      id: "3",
      name: "Ms. Riddhi Patel",
      specialization: "Psychologist",
      experience: "12 years experience overall",
      location: "Vileparle West, Mumbai  Psychoknowmics Educational And Counseling ",
      rating: 98,
      reviews: 82,
      available: "Available Today",
      image: require("../assets/images/ms-riddhi-patel.jpg"),
    },
    {
      id: "4",
      name: "Ms. Mithila Desai",
      specialization: "Psychologist",
      experience: "37 years experience overall",
      location: "Borivali West, Mumbai  Dr Mithila Desai's Power Of Mind Clinic",
      rating: 93,
      reviews: 107,
      available: "Available Today",
      image: require("../assets/images/ms-mithila-desai.jpg"),
    },
    {
      id: "5",
      name: "Ms. Rashi Laskari",
      specialization: "Psychologist",
      experience: "16 years experience overall",
      location: "Andheri West, Mumbai  Inner Light Counselling Centre",
      rating: 97,
      reviews: 99,
      available: "Available Today",
      image: require("../assets/images/ms-rashi-laskari.jpg"),
    },
    {
      id: "6",
      name: "Ms. Mahima Pawar",
      specialization: "Psychologist",
      experience: "9 years experience overall",
      location: "Andheri East, Mumbai  Evolve Wellness",
      rating: 100,
      reviews: 17,
      available: "Available Today",
      image: require("../assets/images/ms-mahima-pawar.jpg"),
    },
  ];
  
  export default therapistsData;
  